// src/frontend/pages/account/get/UserCard.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Card from '../../../components/react/Card';
import Flex from '../../../components/react/Flex';

export default function UserCard({ avatarUrl, displayName, username }) {
  return (
    <Card>
      <div className="layout row">
        <Flex className="xs12 md2 lg1">
          <img src={avatarUrl} alt="Avatar Icon" style={{ minHeight: '50px' }} />
        </Flex>
        <Flex className="xs12 md8 lg11">
          <div className="card__title pb-0">
            <div className="headline mb-0">
              <span className="bold">Name: </span>{ displayName }
            </div>
          </div>
          <div className="card__text pt-1">
            <div><span className="bold">Username: </span>{ username }</div>
          </div>
        </Flex>
      </div>
    </Card>
  );
}

UserCard.propTypes = {
  avatarUrl: PropTypes.string.isRequired,
  displayName: PropTypes.string.isRequired,
  username: PropTypes.string.isRequired,
};

// src/frontend/pages/account/get/UserCard.vue
<template>
    <v-card>
        <v-layout row>
            <v-flex xs12 md2 lg1>
                <img :src="avatarUrl" />
            </v-flex>
            <v-flex xs12 md8 lg11>
                <v-card-title class="pb-0">
                    <div class="headline mb-0">
                        <span class="bold">Name: </span>{{ name }}</div>
                </v-card-title>
                <v-card-text class="pt-1">
                    <div>
                        <span class="bold">Username: </span>{{ username }}</div>
                </v-card-text>
            </v-flex>
        </v-layout>
    </v-card>
</template>

<style scoped lang="stylus">
    img {
        min-height: 50px
    }
    .bold {
        font-weight: 500
    }
    .headline {
        font-weight: normal
    }
</style>

<script>
  export default {
    props: {
      name: {
        type: String,
        required: true,
      },
      avatarUrl: {
        type: String,
        required: true,
      },
      username: {
        type: String,
        required: true,
      },
    },
  };
</script>
